### ISSUE TITLE
No new challenge after reached "Remote"

### ISSUE THREAD

**Issue by mphan17** [NimSum/git-commander#50]
**Recreate the issue:**
1. play the game.
2. Make it to "Remote" place.
3. Congrats message show up, hit continue to play the game
4. Question A show up, answer it correctly

**Expected:**
Question B shows up.

**Actual:**
Question A show up again and again and again.

**Note**
Check out the history box on the screen, it shows the same challenge question

![2019-05-18](https://user-images.githubusercontent.com/25966607/57973599-ff6ad400-7970-11e9-8c33-1e550e2afc51.png)

**Comment by NimSum** [comment]
This problem linked to #55 , fixed the issue of the recurring questions during the current session so if #55 is closed, this will automatically be resolved
